Work section,about me & contact me
UsirusenIkon/Portfolio pull request #2
Opened 2022-08-19 19:03 UTC by UsirusenIkon

In this pull request for the second milestone of the mobile version I initialized and added:

- linters and run checks (stylelint,webhint etc).
- created the work section, about me & contact me section.
- implemented the required design from the figma template.

2022-08-19 23:04 UTC, tugsem requested changes
Hi @UsirusenIkon , 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!
![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights ⭐ 
✔️ You documented your work professionally
✔️ Descriptive PR, branch name and commits
✔️Linters set up correctly and all passing
✔️ Your code is clean and DRY

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- [ ] I highly recommend starting  commit messages with infinitive verbs on your commits to provide more direct and clean messages to reader.
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 23:04 UTC, tugsem commented on index.html
> +  <div class="work-section grid">
- [ ] Kindly use section tag here instead of div since it makes your HTML more readable and semantically correct.

2022-08-19 23:04 UTC, tugsem commented on style.css
> +}
- [ ] Kidly remove the extra space between the last card and about me section to increase the user experience.
Your design: 
![image](https://user-images.githubusercontent.com/91486791/185717217-8becbcb5-33c4-4d8f-b3f9-1ef9e2cf6603.png)
figma design:
![image](https://user-images.githubusercontent.com/91486791/185717235-ff27e7c8-b661-4a7e-924e-80477fe17703.png)

2022-08-19 23:48 UTC, mgmediaweb commented on style.css
> +}
- Kindly, I recommend you follow the advice of the previous reviewer, it will help you a lot to make your site look and work better.

2022-08-19 23:49 UTC, mgmediaweb commented on index.html
> +  <div class="work-section grid">
Good job following the advice of the previous reviewer.

2022-08-19 23:53 UTC, mgmediaweb requested changes
Hi  @UsirusenIkon , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 💯 

- Professional README file. ✔️
- PR has a good title and summary. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 06:09 UTC, frank1738 approved these changes
Hi @UsirusenIkon , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 07:21 UTC, merged